package cn.com.sinosoft.formdesign.model;

// Generated 2015-3-4 10:00:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TFormdesignForm generated by hbm2java
 */
public class TFormdesignForm implements java.io.Serializable {

	private String id;
	private String title;
	private byte[] contentSrc;
	private byte[] content;
	private Date dtCreate;
	private Date dtUpdate;
	private String isPub;

	public TFormdesignForm() {
	}

	public TFormdesignForm(String id, String title, byte[] contentSrc,
			byte[] content, Date dtCreate, Date dtUpdate, String isPub) {
		this.id = id;
		this.title = title;
		this.contentSrc = contentSrc;
		this.content = content;
		this.dtCreate = dtCreate;
		this.dtUpdate = dtUpdate;
		this.isPub = isPub;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public byte[] getContentSrc() {
		return this.contentSrc;
	}

	public void setContentSrc(byte[] contentSrc) {
		this.contentSrc = contentSrc;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	public Date getDtCreate() {
		return this.dtCreate;
	}

	public void setDtCreate(Date dtCreate) {
		this.dtCreate = dtCreate;
	}

	public Date getDtUpdate() {
		return this.dtUpdate;
	}

	public void setDtUpdate(Date dtUpdate) {
		this.dtUpdate = dtUpdate;
	}

	public String getIsPub() {
		return this.isPub;
	}

	public void setIsPub(String isPub) {
		this.isPub = isPub;
	}

}
